const STORAGE_KEY='operations-dashboard-units-v1';
const LAST_CODE_REFRESH_KEY='operations-dashboard-last-code-refresh-v1';
const CODE_REFRESH_MS=30*60*1000;
const REFRESHABLE_UNITS=new Set(['سين','سين 1','باء','باء 1','جيم 1','جيم 2']);
const REFRESHABLE_CODE_COUNTS={'سين 1':5,'سين':4,'باء 1':4,'باء':4,'جيم 1':3,'جيم 2':3};
const FIXED_REPORT_ORDER=['قيادة','إشراف عام','مشرف ميداني','العمليات','نائب العمليات','سين 1','سين','باء 1','باء','جيم 1','جيم 2','دعم','الميناء','وحدات البحث والإنقاذ','تسجيل خروج'];
let units=loadUnits();
const $=id=>document.getElementById(id);
function normalizeUnit(u){let codes=Array.isArray(u.codes)?u.codes.slice():String(u.code||'').split(' / ').filter(Boolean);if(!codes.length)codes=[''];return {...u,codes,code:codes.join(' / ')};}
function loadUnits(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY));if(Array.isArray(saved))return saved.map(normalizeUnit);}catch(e){}return structuredClone(window.DEFAULT_UNITS).map(normalizeUnit);}
function saveUnits(){localStorage.setItem(STORAGE_KEY,JSON.stringify(units));}
function toEnglishDigits(value){return String(value??'').replace(/[٠-٩]/g,d=>String('٠١٢٣٤٥٦٧٨٩'.indexOf(d))).replace(/[۰-۹]/g,d=>String('۰۱۲۳۴۵۶۷۸۹'.indexOf(d)));}
function now(){const d=new Date();const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return{date:`${day}/${m}/${y}`,time24:d.toTimeString().slice(0,5),day:['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'][d.getDay()]};}
function formatEnglishDate(value){value=toEnglishDigits(value).trim();if(!value)return '—';if(/^\d{4}-\d{2}-\d{2}$/.test(value)){const [y,m,d]=value.split('-');return `${d}/${m}/${y}`;}return value;}
function formatArabicTime(value){value=toEnglishDigits(value).trim();if(!value)return '—';const match=value.match(/^(\d{1,2}):(\d{2})\s*(ص|م|AM|PM)?$/i);if(!match)return value;let h=Number(match[1]);const m=match[2];let suffix=match[3];if(suffix){suffix=/^(م|PM)$/i.test(suffix)?'م':'ص';}else{suffix=h>=12?'م':'ص';}h=h%12||12;return `${String(h).padStart(2,'0')}:${m} ${suffix}`;}
function setNow(){const n=now();$('reportDate').value=n.date;$('reportTime').value=n.time24;$('reportDay').value=n.day;updatePreview();}
function addCode(index){units[index].codes.push('');syncUnitCode(index);saveUnits();renderUnits();const inputs=document.querySelectorAll(`[data-code-index="${index}"]`);inputs[inputs.length-1]?.focus();}
function removeCode(index,codeIndex){const required=REFRESHABLE_CODE_COUNTS[units[index].name];if(required&&units[index].codes.length<=required)return;if(units[index].codes.length<=1)return;units[index].codes.splice(codeIndex,1);syncUnitCode(index);saveUnits();renderUnits();}
function syncUnitCode(index){units[index].code=units[index].codes.join(' / ');}
function renderUnits(){const html=[];units.forEach((raw,i)=>{const u=normalizeUnit(raw);units[i]=u;html.push(`<div class="unit-row"><div class="unit-name-wrap"><span class="unit-name">${escapeHtml(u.name)}</span></div><div class="codes-stack">${u.codes.map((code,j)=>`<div class="code-line"><input class="unit-code-input" data-code-index="${i}" data-code-item="${j}" value="${escapeAttr(code)}" placeholder="E-000" aria-label="كود ${escapeAttr(u.name)} ${j+1}" />${u.codes.length>1&&!(REFRESHABLE_CODE_COUNTS[u.name]&&u.codes.length<=REFRESHABLE_CODE_COUNTS[u.name])?`<button class="remove-code" data-remove-code="${i}" data-remove-item="${j}" title="حذف الكود">×</button>`:''}</div>`).join('')}</div><div class="unit-add-row"><button class="add-inline" data-add-code="${i}" title="إضافة كود">＋ إضافة كود</button></div></div>`);});$('unitList').innerHTML=html.join('');document.querySelectorAll('[data-code-index]').forEach(input=>input.addEventListener('input',e=>{const i=+e.target.dataset.codeIndex,j=+e.target.dataset.codeItem;units[i].codes[j]=e.target.value.trim();syncUnitCode(i);handleLogoutCodeChange(i);saveUnits();updatePreview();}));document.querySelectorAll('[data-add-code]').forEach(b=>b.addEventListener('click',()=>addCode(+b.dataset.addCode)));document.querySelectorAll('[data-remove-code]').forEach(b=>b.addEventListener('click',()=>removeCode(+b.dataset.removeCode,+b.dataset.removeItem)));renderAdmin();updatePreview();}
function handleLogoutCodeChange(index){const unit=units[index];if(unit.name!=='تسجيل خروج')return;const logoutCodes=new Set(unit.codes.map(c=>c.trim()).filter(Boolean));if(!logoutCodes.size)return;units.forEach((u,i)=>{if(i===index||!Array.isArray(u.codes))return;u.codes=u.codes.map(c=>logoutCodes.has(c.trim())?'':c);syncUnitCode(i);});}
function renderAdmin(){$('adminList').innerHTML=units.map((u,i)=>`<div class="admin-row"><span>${i+1}</span><input data-index="${i}" data-field="name" value="${escapeAttr(u.name)}" /><input data-index="${i}" data-field="code" value="${escapeAttr(u.code||'')}" placeholder="E-000 / E-000" /><button data-delete="${i}">حذف</button></div>`).join('');document.querySelectorAll('#adminList input').forEach(el=>el.addEventListener('input',e=>{const i=+e.target.dataset.index,f=e.target.dataset.field;if(f==='code'){units[i].codes=e.target.value.split('/').map(s=>s.trim()).filter(Boolean);if(!units[i].codes.length)units[i].codes=[''];}units[i][f]=e.target.value;syncUnitCode(i);handleLogoutCodeChange(i);saveUnits();renderUnits();}));document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{units.splice(+b.dataset.delete,1);saveUnits();renderUnits();}));}
function shuffle(arr){for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]];}return arr;}
function refreshCodes(showToast=true){units=units.map(normalizeUnit);const active=units.filter(u=>REFRESHABLE_UNITS.has(u.name));const slots=[];active.forEach(u=>u.codes.forEach((code,index)=>{if(String(code||'').trim())slots.push({code:String(code).trim(),from:u.name,index});}));if(slots.length>1){let shuffled;for(let attempt=0;attempt<100;attempt++){shuffled=shuffle(slots.slice());let valid=true,p=0;for(const u of active){for(let i=0;i<u.codes.filter(c=>String(c||'').trim()).length;i++){if(shuffled[p++].from===u.name){valid=false;break;}}if(!valid)break;}if(valid)break;}let p=0;active.forEach(u=>{const count=u.codes.filter(c=>String(c||'').trim()).length;u.codes=[];for(let i=0;i<count;i++)u.codes.push(shuffled[p++].code);});units.forEach((u,i)=>syncUnitCode(i));}saveUnits();localStorage.setItem(LAST_CODE_REFRESH_KEY,String(Date.now()));renderUnits();updateRefreshStatus();if(showToast)toast('تم نقل الأكواد الموجودة إلى أماكن جديدة بدون إضافة أو حذف');}
function updateRefreshStatus(){const el=$('codeRefreshStatus');if(!el)return;const last=+(localStorage.getItem(LAST_CODE_REFRESH_KEY)||0);if(!last){el.textContent='التحديث كل 30 دقيقة — نقل الأكواد فقط';return;}const r=Math.max(0,CODE_REFRESH_MS-(Date.now()-last));if(!r){el.textContent='جاهز للتحديث — سيتم نقل الأكواد فقط';return;}el.textContent=`التحديث القادم بعد ${Math.floor(r/60000)}:${String(Math.floor(r%60000/1000)).padStart(2,'0')} — الأكواد لا تتغير`;}
function checkAutoCodeRefresh(){const last=+(localStorage.getItem(LAST_CODE_REFRESH_KEY)||0);if(last&&Date.now()-last>=CODE_REFRESH_MS)refreshCodes(true);updateRefreshStatus();}
function formatReportSection(unit){const codes=(Array.isArray(unit.codes)?unit.codes:[]).map(c=>String(c).trim()).filter(Boolean);if(!codes.length)return `${unit.name}: —`;return `${unit.name}:\n${codes.join('\n')}`;}
function updatePreview(){const no=toEnglishDigits($('reportNo').value)||'—',day=$('reportDay').value||'—',date=formatEnglishDate($('reportDate').value),time=formatArabicTime($('reportTime').value);const byName=new Map(units.map(u=>[u.name,u]));const ordered=FIXED_REPORT_ORDER.map(name=>byName.get(name)).filter(Boolean);$('reportPreview').textContent=`تم تحديث تقرير عمليات ( ساندي و بوليتو ) رقم ( ${no} ) في تمام الساعه ( ${time} ) في يوم ( ${day} ) التاريخ ${date}\n\n`+ordered.map(formatReportSection).join('\n\n');}
function escapeHtml(s){return String(s??'').replace(/[&<>"\\]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]||c));}
function escapeAttr(s){return escapeHtml(s).replace(/'/g,'&#39;');}
['reportNo','reportDay','reportDate','reportTime'].forEach(id=>$(id).addEventListener('input',e=>{e.target.value=e.target.value.replace(/[٠-٩۰-۹]/g,d=>toEnglishDigits(d));updatePreview();}));
$('refreshTime').addEventListener('click',setNow);$('refreshCodes').addEventListener('click',()=>refreshCodes(true));$('copyReport').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('reportPreview').textContent);toast('تم نسخ التقرير بنجاح');}catch(e){toast('تعذر النسخ تلقائياً');}});$('addUnit').addEventListener('click',()=>{units.push({name:'وحدة جديدة',code:'',codes:['']});saveUnits();renderUnits();});$('resetUnits').addEventListener('click',()=>{if(confirm('إعادة الوحدات الافتراضية؟')){units=structuredClone(window.DEFAULT_UNITS).map(normalizeUnit);saveUnits();renderUnits();}});document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(btn.dataset.view==='report'?'reportView':'unitsView').classList.add('active');$('pageTitle').textContent=btn.dataset.view==='report'?'التقرير الرئيسي':'إدارة الوحدات';}));function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}setNow();renderUnits();updateRefreshStatus();setInterval(checkAutoCodeRefresh,1000);